version: "2"

run:
  linters:
    enable:
      - errcheck
      - gosimple
      - govet
      - ineffassign
      - staticcheck
      - unused
      - typecheck
      - gocritic
      - gocyclo
      - nolintlint
